version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      linters:
        patterns:
          - '*eslint*'
          - '*prettier*'
      typescript:
        dependency-type: 'development'
        patterns:
          - 'typescript'
      types:
        patterns:
          - '@types/*'
          - 'type-fest'
      guardian:
        patterns:
          - '@guardian/*'
      dependenciesMinor:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '@guardian/*'
          - '@types/*'
          - 'type-fest'
          - '*eslint*'
          - '*prettier*'
          - 'typescript'
      devDependenciesMinor:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '@guardian/*'
          - '@types/*'
          - 'type-fest'
          - '*eslint*'
          - '*prettier*'
          - 'typescript'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    groups:
      actionsMinor:
        update-types:
          - minor
          - patch
      actionsMajor:
        update-types:
          - major
  - package-ecosystem: 'pip'
    directory: '/scripts/deploy'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
