export const gamVariables = {
	SeriesURL: 'advertiser-content/we-are-still-in/we-are-still-in',
	BrandLogo: '',
	BrandColour: '#d90c1f',
	TrackingId: '',
	Article1Headline: '',
	Article1Image: '',
	Article1URL: '',
	Article2Headline: '',
	Article2Image: '',
	Article2URL: '',
	Article3Headline: '',
	Article3Image: '',
	Article3URL: '',
	Article4Headline: '',
	Article4Image: '',
	Article4URL: '',
	numberOfElements: '1',
};
