export const gamVariables = {
	SeriesURL: 'advertiser-content/advent-zagreb/advent-zagreb',
	BrandLogo: '',
	BrandColour: '#222B5E',
	TrackingId: '',
	Article1Headline: '',
	Article1Image: '',
	Article1URL: '',
	Article2Headline: '',
	Article2Image: '',
	Article2URL: '',
	Article3Headline: '',
	Article3Image: '',
	Article3URL: '',
	Article4Headline: '',
	Article4Image: '',
	Article4URL: '',
	numberOfElements: '4',
};
