import type { ScrollType } from '$lib/types/background';

export const gamVariables = {
	ClickthroughUrl: '',
	ScrollType: 'none' as ScrollType,
	ShowMoreType: '',
	BackgroundColour: '',
	BackgroundImage: '',
	BackgroundImagePosition: '',
	BackgroundImageRepeat: '',
	MobileBackgroundImage: '',
	MobileBackgroundImagePosition: '',
	MobileBackgroundImageRepeat: '',
	Slide1BackgroundColour: '',
	Slide1BackgroundImage: '',
	Slide1BackgroundRepeat: '',
	Slide1BackgroundPosition: '',
	Slide1MobileBackgroundImage: '',
	Slide1MobileBackgroundRepeat: '',
	Slide1MobileBackgroundPosition: '',
	Slide1Layer1BackgroundImage:
		'https://tpc.googlesyndication.com/simgad/17554758987417110030?',
	Slide1Layer1BackgroundRepeat: 'no-repeat',
	Slide1Layer1BackgroundPosition: 'center center',
	Slide1Layer1MobileBackgroundImage:
		'https://tpc.googlesyndication.com/simgad/12472120302988849309?',
	Slide1Layer1MobileBackgroundRepeat: 'no-repeat',
	Slide1Layer1MobileBackgroundPosition: 'center center',
	Slide1Layer2BackgroundImage:
		'https://tpc.googlesyndication.com/simgad/17554758987417110030?',
	Slide1Layer2BackgroundRepeat: 'no-repeat',
	Slide1Layer2BackgroundPosition: 'center center',
	Slide1Layer2MobileBackgroundImage: '',
	Slide1Layer2MobileBackgroundRepeat: '',
	Slide1Layer2MobileBackgroundPosition: '',
	Slide1Layer3BackgroundImage: '',
	Slide1Layer3BackgroundRepeat: '',
	Slide1Layer3BackgroundPosition: '',
	Slide1Layer3MobileBackgroundImage: '',
	Slide1Layer3MobileBackgroundRepeat: '',
	Slide1Layer3MobileBackgroundPosition: '',
	Slide2BackgroundColour: '',
	Slide2BackgroundImage: '',
	Slide2BackgroundRepeat: '',
	Slide2BackgroundPosition: '',
	Slide2MobileBackgroundImage: '',
	Slide2MobileBackgroundRepeat: '',
	Slide2MobileBackgroundPosition: '',
	Slide2Layer1BackgroundImage:
		'https://tpc.googlesyndication.com/simgad/4655436357172306837?',
	Slide2Layer1BackgroundRepeat: 'no-repeat',
	Slide2Layer1BackgroundPosition: 'center center',
	Slide2Layer1MobileBackgroundImage:
		'https://tpc.googlesyndication.com/simgad/2232758949767305138?',
	Slide2Layer1MobileBackgroundRepeat: 'no-repeat',
	Slide2Layer1MobileBackgroundPosition: 'center center',
	Slide2Layer2BackgroundImage:
		'https://tpc.googlesyndication.com/simgad/7054833562526198004?',
	Slide2Layer2BackgroundRepeat: 'no-repeat',
	Slide2Layer2BackgroundPosition: 'bottom left',
	Slide2Layer2MobileBackgroundImage:
		'https://tpc.googlesyndication.com/simgad/7268971793572049255?',
	Slide2Layer2MobileBackgroundRepeat: 'no-repeat',
	Slide2Layer2MobileBackgroundPosition: 'bottom left',
	Slide2Layer3BackgroundImage: '',
	Slide2Layer3BackgroundRepeat: '',
	Slide2Layer3BackgroundPosition: '',
	Slide2Layer3MobileBackgroundImage: '',
	Slide2Layer3MobileBackgroundRepeat: '',
	Slide2Layer3MobileBackgroundPosition: '',
	Trackingpixel: '',
	Researchpixel: '',
	Viewabilitypixel: '',
};
