name: Deploy Test Templates to GAM

permissions:
  contents: read

concurrency:
  group: 'deploy-test'
  cancel-in-progress: true

on:
  pull_request:
    types: [labeled]

jobs:
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    if: github.event.label.name == 'deploy-test'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: corepack enable
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Build
        run: pnpm build:templates

      - name: Deploy Templates to GAM (Test)
        run: pnpm deploy:gam:test --ci
        env:
          GAM_APPLICATION_NAME: ${{ secrets.GAM_APPLICATION_NAME }}
          GAM_NETWORK_CODE: ${{ secrets.GAM_NETWORK_CODE }}
          SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.SERVICE_ACCOUNT_KEY_FILE }}
