# This action runs snyk monitor on every push to main
name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-commercial
      SKIP_NODE: false
      SKIP_PYTHON: false
      PYTHON_VERSION: 3.11
      PIPFILES: scripts/deploy/Pipfile
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
